
version: "3.9"
services:
  redis:
    image: "redis:alpine"
    environment:
      - REDIS_PASSWORD=pass
      - REDIS_REPLICATION_MODE=master
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/data
    command:
      - "--save 10 100"
      - "--requirepass pass"

    healthcheck:
      test: redis-cli ping
      interval: 3s
      timeout: 5s
      retries: 5

  redisinsight:
    image: redislabs/redisinsight
    ports:
      # http://localhost:8001/
      - 8001:8001
    volumes:
      - redisinsight:/db

  # api: # Traveling Salesman Optimization api.
  #   container_name: api
  #   build:
  #     context: ./
  #     dockerfile: Dockerfile
  #   ports:
  #     - 5000:5000
  #   depends_on:
  #     - redis
  #   env_file:
  #     - env
  #   network_mode: host

volumes:
  redis:
  redisinsight:
